class Courses {
  static const List<String> courseList = [
    'BS Computer Science',
    'BS Information Technology',
    'BS Information Systems',
    'BS Computer Engineering',
    'BS Electronics Engineering',
    'BS Electrical Engineering',
    'BS Civil Engineering',
    'BS Mechanical Engineering',
    'BS Industrial Engineering',
    'BS Architecture',
    'BS Accountancy',
    'BS Business Administration',
    'BS Management',
    'BS Marketing',
    'BS Finance',
    'BS Economics',
    'BS Psychology',
    'BS Education',
    'BS Nursing',
    'BS Medical Technology',
    'BS Pharmacy',
    'BS Biology',
    'BS Chemistry',
    'BS Mathematics',
    'BS Physics',
    'BS Statistics',
    'BA Communication',
    'BA English',
    'BA History',
    'BA Political Science',
    'BA Sociology',
    'BA Philosophy',
    'BS Agriculture',
    'BS Forestry',
    'BS Environmental Science',
    'BS Hotel and Restaurant Management',
    'BS Tourism',
    'BS Criminology',
    'BS Social Work',
  ];

  static const List<String> yearLevels = [
    '1st Year',
    '2nd Year',
    '3rd Year',
    '4th Year',
    '5th Year',
  ];
}

